In [2]:
import numpy as np
seed = 47

In [3]:
#Task 1
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [4]:
#Task 2
x = np.zeros((5,5))
x += np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [5]:
[[j for j in range(5)] for i in range(5)]

[[0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4]]

In [6]:
#Task 3
x = np.random.random((3,3,3))
x

array([[[0.81926951, 0.33872775, 0.39052432],
        [0.55798349, 0.93868063, 0.38516576],
        [0.98110077, 0.0070647 , 0.67694063]],

       [[0.05070721, 0.06287338, 0.89275337],
        [0.21709235, 0.42594027, 0.0843733 ],
        [0.56677208, 0.00509528, 0.52872028]],

       [[0.55453722, 0.48459787, 0.61141875],
        [0.46397528, 0.33415121, 0.18973857],
        [0.2882955 , 0.38008023, 0.05717768]]])

In [7]:
#Task 4
x = np.ones((4, 4))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [8]:
#Task 5
x = np.random.random(10)
x

array([0.98706409, 0.27491855, 0.77278815, 0.44441683, 0.58374733,
       0.9663571 , 0.15926786, 0.31665959, 0.0278508 , 0.47715656])

In [9]:
sorted(x, reverse=True)

[0.9870640948331059,
 0.9663571031975245,
 0.7727881508127967,
 0.5837473326393845,
 0.47715655855848416,
 0.44441683275444344,
 0.3166595869762998,
 0.2749185496879969,
 0.1592678628438451,
 0.027850802505735905]

In [10]:
#Task 6
a = np.random.random((2, 2, 2))
print(a)
a.shape

[[[0.26897457 0.85960693]
  [0.46259562 0.62062347]]

 [[0.56293393 0.42988701]
  [0.58818203 0.54113464]]]


(2, 2, 2)

In [11]:
import pandas as pd

In [12]:
#Task 7-8
df = pd.read_csv('adult.csv')
df.head(2)

age         workclass  education_num      marital_status       occupation  \
0   39         State-gov             13       Never-married     Adm-clerical   
1   50  Self-emp-not-inc             13  Married-civ-spouse  Exec-managerial   

    relationship   race gender  hours_per_week native_country  capital  \
0  Not-in-family  White   Male              40  United-States     2174   
1        Husband  White   Male              13  United-States        0   

  income_status  
0         <=50K  
1         <=50K

In [13]:
df.tail(2)

age     workclass  education_num      marital_status       occupation  \
45220   44       Private             13            Divorced     Adm-clerical   
45221   35  Self-emp-inc             13  Married-civ-spouse  Exec-managerial   

      relationship   race gender  hours_per_week native_country  capital  \
45220    Own-child  Other   Male              40  United-States     5455   
45221      Husband  White   Male              60  United-States        0   

      income_status  
45220         <=50K  
45221          >50K

In [14]:
df.shape

(45222, 12)

In [15]:
df.describe()

age  education_num  hours_per_week       capital
count  45222.000000   45222.000000    45222.000000  45222.000000
mean      38.547941      10.118460       40.938017   1012.834925
std       13.217870       2.552881       12.007508   7530.315380
min       17.000000       1.000000        1.000000  -4356.000000
25%       28.000000       9.000000       40.000000      0.000000
50%       37.000000      10.000000       40.000000      0.000000
75%       47.000000      13.000000       45.000000      0.000000
max       90.000000      16.000000       99.000000  99999.000000

In [23]:
#Task 9
from sklearn import preprocessing

df2 = pd.read_csv('df_test.csv')

X = df2['sepal_length_cm']

X = X.values.reshape(-1,1)

minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))

X_scaled = minmax_scale.fit_transform(X)

X_scaled

array([[0.22222222],
       [0.16666667],
       [0.11111111],
       [0.08333333],
       [0.19444444],
       [0.30555556],
       [0.08333333],
       [0.19444444],
       [0.02777778],
       [0.16666667],
       [0.30555556],
       [0.13888889],
       [0.13888889],
       [0.        ],
       [0.41666667],
       [0.38888889],
       [0.30555556],
       [0.22222222],
       [0.38888889],
       [0.22222222],
       [0.30555556],
       [0.22222222],
       [0.08333333],
       [0.22222222],
       [0.13888889],
       [0.19444444],
       [0.19444444],
       [0.25      ],
       [0.25      ],
       [0.11111111],
       [0.13888889],
       [0.30555556],
       [0.25      ],
       [0.33333333],
       [0.16666667],
       [0.19444444],
       [0.33333333],
       [0.16666667],
       [0.02777778],
       [0.22222222],
       [0.19444444],
       [0.05555556],
       [0.02777778],
       [0.19444444],
       [0.22222222],
       [0.13888889],
       [0.22222222],
       [0.083

Я не знаю почему так выходит, но так выходит
Я прогнал на пробных данных ниже и все прекрасно получается...

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0                5.1             3.5              1.4             0.2   
1                4.9             3.0              1.4             0.2   
2                4.7             3.2              1.3             0.2   
3                4.6             3.1              1.5             0.2   
4                5.0             3.6              1.4             0.2   
..               ...             ...              ...             ...   
145              6.7             3.0              5.2             2.3   
146              6.3             2.5              5.0             1.9   
147              6.5             3.0              5.2             2.0   
148              6.2             3.4              5.4             2.3   
149              5.9             3.0              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [18]:
df3 = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))

X_scaled = minmax_scale.fit_transform(df3)

X_scaled

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [19]:
scaler = preprocessing.StandardScaler()

X2_scaled = scaler.fit_transform(df3)

X2_scaled

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])